disabled_rules: # rule identifiers to exclude from running
  - comment_spacing
  - trailing_whitespace
  - type_name
  - todo
  - large_tuple
  - nesting

opt_in_rules:
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - first_where
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - strong_iboutlet
  - vertical_parameter_alignment_on_call
  - void_return

line_length:
  warning: 160
